### ISSUE TITLE
geopandas: can't save file without specifying driver

### ISSUE THREAD

**Issue by kadyb** [kadyb/vector-benchmark#6]
I updated `{geopandas}` to 0.10.2 and tried to save geodataframe to geopackage without specifying the driver. However, I get this error: 

```python
> cd vector-benchmark
> ./run_benchmarks.sh

/home/krzdyb/.local/lib/python3.8/site-packages/geopandas/_compat.py:111: UserWarning: The Shapely GEOS version (3.10.2-CAPI-1.16.0) is incompatible with the GEOS version PyGEOS was compiled with (3.10.1-CAPI-1.16.0). Conversions between both will be slow.
  warnings.warn(
Traceback (most recent call last):
  File "geopandas/write.py", line 17, in <module>
    gdf.to_file(tmp)
  File "/home/krzdyb/.local/lib/python3.8/site-packages/geopandas/geodataframe.py", line 1114, in to_file
    _to_file(self, filename, driver, schema, index, **kwargs)
  File "/home/krzdyb/.local/lib/python3.8/site-packages/geopandas/io/file.py", line 374, in _to_file
    driver = _detect_driver(filename)
  File "/home/krzdyb/.local/lib/python3.8/site-packages/geopandas/io/file.py", line 286, in _detect_driver
    return _EXTENSION_TO_DRIVER[Path(path).suffix.lower()]
  File "/usr/lib/python3.8/pathlib.py", line 1042, in __new__
    self = cls._from_parts(args, init=False)
  File "/usr/lib/python3.8/pathlib.py", line 683, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/lib/python3.8/pathlib.py", line 667, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not int
```

Here is script: https://github.com/kadyb/vector-benchmark/blob/main/geopandas/write.py
If I specify the driver, it works fine. @martinfleis, could you look into this?

**Comment by martinfleis** [comment]
`tempfile.Tempfile` used in the script is an `_io.BufferedRandom` object. We assume a path that can be passed to `pathlib.Path` so we can extract a suffix from it. You can create tempdir and save to that.

```py
with tempfile.TemporaryDirectory() as tmpdir:
    filename = os.path.join(tmpdir, "test_file.gpkg")
    gdf.to_file(filename)
```

**Comment by martinfleis** [comment]
Btw, that warning you see

```
UserWarning: The Shapely GEOS version (3.10.2-CAPI-1.16.0) is incompatible with the GEOS version PyGEOS was compiled with (3.10.1-CAPI-1.16.0). Conversions between both will be slow.
```

may potentially affect the benchmark results as your environment now requires expensive conversion between shapely and pygeos objects in some cases.

**Comment by kadyb** [comment]
Thanks!

> may potentially affect the benchmark results as your environment now requires expensive conversion between shapely and pygeos objects in some cases.

I just noticed that load and save operations are taking longer than before. I downloaded these packages from PIP - do they come with their own GEOS binary versions? I suppose the solution is to compile the sources.

**Comment by martinfleis** [comment]
> do they come with their own GEOS binary versions? I suppose the solution is to compile the sources.

Yes and yes.

**Comment by kadyb** [comment]
One interesting thing, it works on Windows 8.1:

```python
tmp = tempfile.TemporaryFile(suffix = ".gpkg")
gdf.to_file(tmp)
```

but it's probably because `tempfile.Tempfile` works differently on different OSes.
